data:
  name: 'Wave2D-0000'
  total_num: 10
  n_train: 8
  n_test: 2
  nx: 128
  nt: 100
  sub: 1
  sub_t: 1
  c: 1.0

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128
  activation: 'gelu'
  padding: 5

train:
  batchsize: 1
  epochs: 100
  milestones: [25, 50, 75, 100]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 5.0
  f_loss: 1.0
  xy_loss: 5.0
  save_dir: 'Wave2D'
  save_name: 'Wave2D-0000.pt'
  ckpt: 'checkpoints/Wave2D.pt'
  ckpt_freq: 25

log:
  project: 'PINO-Wave'
  group: 'Wave2D'

test:
  batchsize: 1
  ckpt: 'checkpoints/Wave2D.pt'